swagger: '2.0'
info:
  title: Good Pone Points
  description: The API for the Good Pone Points service.
host: points.horse
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
